timeline
    title Evolução da Navegação em Aplicativos Android

    2008 : Navegação com startActivity()
         : Cada tela é uma Activity independente
    2011 : Surgimento dos Fragments (Honeycomb)
         : Uma Activity controla múltiplos fragments
         : Começa o conceito de “back stack” manual
    2018 : Navigation Component (NavHost, NavController)
         : Grafo de navegação, Safe Args, Deep Links
         : Simplificação da navegação com Fragments
    2020 : Jetpack Compose introduz sua própria navegação
         : NavHostController para destinos composables
         : Navegação declarativa
    2024 : Navigation 3
         : Rotas compostáveis, fluxo centrado em *screens*
         : State-driven navigation, mais simples, mais previsível

